[package]
name=pascaltest
version=0.1.0

[clean]
units=PascalTest

[compiler]
targetdir=build
sourcedir=src

[default]
fpcdir=/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin

[target]
programs=PascalTest
